do $$ begin
   create type schema_type as enum('OWL', 'SKOS');
exception
    when duplicate_object then null;
end $$;

create table if not exists profiles(
       id               integer primary key generated by default as identity,
       label            text unique,
       theme            text default '',
       allowed_tools    text[],
       is_shared        boolean default true,
       access_control   json default '{}'::json,
       schema_types     schema_type[]
);

-- Add a view to retrieve the profiles and set the schema_types as texts array
create view profiles_list as
       select label, theme, allowed_tools, access_control, is_shared, schema_types::text[]
       from profiles;
