create type schema_type as enum('OWL', 'SKOS');

create table if not exists profiles(
       id               integer primary key generated by default as identity,
       label            text unique,
       theme            text default '',
       allowed_tools    text[],
       is_shared        boolean default true,
       access_control   json default '{}'::json,
       schema_types     schema_type[]
);
