create type schema_type as enum('OWL', 'SKOS');

create table if not exists profiles(
       id                integer primary key generated by default as identity,
       label             text unique,
       theme             text default '',
       allowed_tools     text[],
       allowed_databases text[],
       is_shared         boolean default true,
       access_control    json default '{}'::json,
       schema_types      schema_type[],
       quota             json default '{}'::json,
       max_nt_export_triples integer,
       create_source     boolean,
       maximum_source    integer,
       -- Null means the profile does not decide, and the user account applies.
       -- Zero is a decision: it forbids.
       max_writable_triples  integer,
       max_upload_triples    integer,
       max_user_data_records integer,
       max_virtuoso_load     integer
 );
