create type authentificator as enum('database', 'keycloak', 'auth0');

create table if not exists users(
       id               integer primary key generated by default as identity,
       login            text unique,
       password         text,
       token            text default '',
       profiles         text[],
       auth             authentificator
);
