create table if not exists user_data(
       id               integer primary key generated by default as identity,
       data_path        text,
       data_type        text,
       data_label       text default '',
       data_comment     text default '',
       data_group       text default '',
       data_content     json default '{}'::json,
       is_shared        boolean default false,
       shared_profiles  text[],
       shared_users     text[],
       created_at       timestamp not null default now(),
       owned_by         integer references users (id)
);
