create table if not exists quota(
    id        integer primary key generated by default as identity,
    user_id   integer references users (id),
    route     text default '',
    timestamp timestamp with time zone
)
