version: "3"
services:
    virtuoso:
        image: askomics/virtuoso:7.2.7
        environment:
            VIRT_SPARQL_DefaultQuery: SELECT DISTINCT ?graph count(?s) as ?number_of_triples WHERE { GRAPH ?graph { ?s ?p ?o . }}
        ports:
            - 8890:8890
        volumes:
            - ./tests/data/rdf:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/dumps
        command: |
            sh /virtuoso/virtuoso.sh &
            sleep 10s
            isql-v -U dba -P dba  <<EOF
                ld_dir('dumps', 'bfo_classes_only.owl', 'http://purl.obolibrary.org/obo/bfo.owl');
                rdf_loader_run();
                exit;
            EOF
        networks:
            - dev-backend

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "superSecretP4ssword"
        networks:
            - dev-backend

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
        ports:
            - 9200:9200
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
        networks:
            - dev-backend

    spacyserver:
        image: neelkamath/spacy-server:2-en_core_web_sm
        ports:
            - 8000:8000
        networks:
            - dev-backend

networks:
    dev-backend:
        driver: "bridge"
