services:
    virtuoso:
        image: askomics/virtuoso:7.2.14
        environment:
            VIRT_SPARQL_DefaultQuery: SELECT DISTINCT ?graph count(?s) as ?number_of_triples WHERE { GRAPH ?graph { ?s ?p ?o . }}
            SPARQL_UPDATE: "true"
            VIRT_SPARQL_MaxDataSourceSize: 100000000
            VIRT_SPARQL_MaxQueryCostEstimationTime: 0
            VIRT_SPARQL_MaxQueryExecutionTime: 0
        ports:
            - 8890:8890
            - 1111:1111
        volumes:
            - ./tests/data/rdf:/usr/local/virtuoso-opensource/var/lib/virtuoso/db/dumps
            - ./docker-data/virtuoso:/data
        command: |
            sh /virtuoso/virtuoso.sh &
            sleep 10s
            isql-v -U dba -P dba  <<EOF
                ld_dir('dumps', 'bfo_classes_only.owl', 'http://purl.obolibrary.org/obo/bfo.owl');
                rdf_loader_run();
                exit;
            EOF
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - dev-backend

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "superSecretP4ssword"
        volumes:
            - ./docker-data/sqlserver:/var/opt/mssql
        networks:
            - dev-backend

    postgres:
        image: postgis/postgis:16-3.4
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "mysecretpassword"
            DATABASE_USER: slsv
            DATABASE_NAME: slsv
            DATABASE_PASSWORD: slsv
        volumes:
            - ./docker-data/postgres:/var/lib/postgresql/data
            - ./scripts/sql:/sql:ro
            - ./scripts/docker-init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        networks:
            - dev-backend

    mariadb:
        image: mariadb:10
        ports:
            - 3306:3306
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_USER: slsv
            MARIADB_PASSWORD: slsv
            MARIADB_DATABASE: slsv
        networks:
            - dev-backend

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26
        ports:
            - 9200:9200
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
            ELASTIC_PASSWORD: toto
            xpack.security.enabled: "true"
        networks:
            - dev-backend

    spacyserver:
        image: neelkamath/spacy-server:2-en_core_web_sm
        ports:
            - 8000:8000
        networks:
            - dev-backend

networks:
    dev-backend:
        driver: "bridge"
