import { getSparqlQueryErrorResponses, getSparqlQueryRequestBodySchema, runRegisteredSparqlQuery } from "../../controllers/sparqlQueries.js";

export default function () {
    async function POST(req, res, _next) {
        return runRegisteredSparqlQuery(req, res, true);
    }

    POST.apiDoc = {
        summary: "Build an exposed SPARQL query request",
        description:
            "Builds the SPARQL request generated by a query function shared from SousLeSens without executing it. " +
            "The function is identified by `name` + `module` from the catalog and called with the provided `params`. " +
            "Use this route when an external client wants to inspect, share, or run the generated SPARQL elsewhere.",
        operationId: "codeRequestSparqlQuery",
        parameters: [
            {
                in: "body",
                name: "body",
                required: true,
                schema: getSparqlQueryRequestBodySchema(),
            },
        ],
        responses: {
            200: {
                description: "Generated SPARQL request returned by the selected exposed function.",
                schema: { $ref: "#/definitions/SparqlQueryResponse" },
            },
            ...getSparqlQueryErrorResponses(),
        },
        security: [{ restrictLoggedUser: [] }],
        tags: ["Sparql queries"],
    };

    return { POST };
}
