#! /bin/bash

psql -v ON_ERROR_STOP=1 <<-EOSQL
  CREATE ROLE ${DATABASE_USER} WITH LOGIN;
  ALTER ROLE ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}';
  CREATE DATABASE ${DATABASE_NAME} OWNER ${DATABASE_USER};
  GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} TO ${DATABASE_USER};
EOSQL

export PGPASSWORD=${DATABASE_PASSWORD}
for f in $(ls -1 /sql/*.sql);do
    psql -v ON_ERROR_STOP=1 --username "${DATABASE_USER}" --dbname "${DATABASE_NAME}" < ${f}
done
