name: Docker build and Kubernetes deploy

on:
    push:
        branches:
            - "master"
        tags:
            - "*.*.*"

jobs:
    docker:
        environment: docker-registry
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  # list of Docker images to use as base name for tags
                  images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REGISTRY_PATH }}
                  # generate Docker tags based on the following events/attributes
                  tags: |
                      type=sha
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ secrets.DOCKER_REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  secrets: |
                      GIT_AUTH_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
    deploy:
        needs:
            - docker
        if: "github.ref == 'refs/heads/master'"
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/helmfile/helmfile:v0.171.0
            env:
                KUBE_TEST: "toto"
                KUBECONFIG_B64: "${{ secrets.KUBECONFIG_B64 }}"
        steps:
            - name: kubeconfig
              run: echo ${KUBECONFIG_B64} | base64 -d > ~/kubeconfig
            - name: helm-upgrade
              run: helm --kubeconfig ~/kubeconfig upgrade souslesens https://helm.logilab.fr/charts/web-app-2.1.0.tgz --wait --atomic --timeout=10m --reuse-values --set=image.tag=sha-${GITHUB_SHA::7}
