name: Docker build and push

on:
    push:
        branches:
            - "chore/deploy-on-k8s"
            - "master"
        tags:
            - "*.*.*"

jobs:
    docker:
        environment: docker-registry
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                  # list of Docker images to use as base name for tags
                  images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REGISTRY_PATH }}
                  # generate Docker tags based on the following events/attributes
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=semver,pattern={{major}}
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ secrets.DOCKER_REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  secrets: |
                      GIT_AUTH_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
    deploy:
        environment: docker-registry
        runs-on: ubuntu-latest
        # needs: docker
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install deps
              run: |
                  mkdir -p ~/.bin
                  # sops
                  curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
                  mv sops-v3.8.1.linux.amd64 ~/.bin/sops
                  chmod +x ~/.bin/sops
                  # age
                  wget https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
                  tar -xvf age-v1.1.1-linux-amd64.tar.gz
                  cp age/age ~/.bin/sops
                  echo ~/.bin >> $GITHUB_PATH
            - name: Configure
              run: |
                  mkdir -p ~/.kube
                  echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
            - name: deploy
              uses: helmfile/helmfile-action@v1.0.0
              with:
                  helm-plugins: >
                      https://github.com/databus23/helm-diff,
                      https://github.com/jkroepke/helm-secrets
                  helmfile-args: apply --file deploy/helmfile.yaml --set image.tag=${{ github.ref }}
              env:
                  KUBECONFIG: ~/.kube/config
                  SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
